---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
unzip("activity.zip")
data <- read.csv("activity.csv")
data$interval <- as.factor(data$interval)

```
## What is mean total number of steps taken per day?
```{r}
dataCom <- data[complete.cases(data),]
sumSteps <- tapply(dataCom$steps, dataCom$date, sum)
sumSteps
hist(sumSteps, breaks = 20, xlab = "Total number of steps per day")
mean(sumSteps, na.rm = TRUE)
median(sumSteps, na.rm = TRUE)
```
## What is the average daily activity pattern?
```{r}
intMean <- tapply(data$steps, data$interval, mean, na.rm = TRUE)
intMean
plot(levels(data$interval), intMean, type = "l", xlab = "5 minute interval", ylab = "Average number of steps")
which.max(intMean)
```

## Imputing missing values
```{r}
sum(is.na(data))

# Replacement of NA with 0 for total steps in interval.
data[is.na(data)] <- 0

totSteps <- tapply(data$steps, data$date, sum)
hist(totSteps, breaks = 20, xlab = "Total number of steps per day")
mean(totSteps, na.rm = TRUE)
median(totSteps, na.rm = TRUE)
```
By replacing the NA values with 0, both the mean and median number of steps taken per day decreased. 

## Are there differences in activity patterns between weekdays and weekends?
```{r}

```